# SIMULATOR = Questa for Mentor's Questasim

SIMULATOR = Questa

RTL= ../rtl/*
work= work #library name
SVTB1= ../top/ring_top.sv
INC = +incdir+../top +incdir+../test +incdir+../agent +incdir+../env
SVTB2 = ../top/ring_pkg.sv
VSIMOPT= -vopt -voptargs=+acc 
VSIMCOV= -coverage -sva 
VSIMBATCH1= -c -do  " log -r /* ;coverage save -onexit mem_cov1;run -all; exit"
VSIMBATCH2= -c -do  " log -r /* ;coverage save -onexit mem_cov2;run -all; exit"
VERBOSITY= +UVM_VERBOSITY=UVM_MEDIUM

help:
	@echo ============================================================================================================
	@echo "! USAGE   	--  make target                  																															!"
	@echo "! clean   	=>  clean the earlier log and intermediate files.  																						!"
	@echo "! sv_cmp    	=>  Create library and compile the code.           																					!"
	@echo "! run_test	=>  clean, compile & run the simulation for base_test in batch mode.													!" 
	@echo "! run_test1	=>  clean, compile & run the simulation for verify_ring_counter_test in batch mode.					!" 
	@echo "! view_wave1 =>  To view the waveform of base_test	    																									!" 
	@echo "! view_wave2 =>  To view the waveform of verify_ring_counter_test	    																								!" 
	@echo "! regress    =>  clean, compile and run all testcases in batch mode.		    															!"
	@echo "! report     =>  To merge coverage reports for all testcases and  convert to html format.								!"
	@echo "! cov        =>  To open merged coverage report in html format.																					!"
	@echo ============================================================================================================

clean 	   : clean_$(SIMULATOR)
sv_cmp     : sv_cmp_$(SIMULATOR)
run_test   : run_test_$(SIMULATOR)
run_test1  : run_test1_$(SIMULATOR)
view_wave1 : view_wave1_$(SIMULATOR)
view_wave2 : view_wave2_$(SIMULATOR)
regress    : regress_$(SIMULATOR)
report     : report_$(SIMULATOR)
cov        : cov_$(SIMULATOR)

# ----------------------------- Start of Definitions for Mentor's Questa Specific Targets -------------------------------#

sv_cmp_Questa:
	vlib $(work)
	vmap work $(work)
	vlog -work $(work) $(RTL) $(INC) $(SVTB2) $(SVTB1) 	
	
run_test_Questa: sv_cmp
	vsim -cvgperinstance $(VSIMOPT) $(VSIMCOV) $(VSIMBATCH1) $(VERBOSITY) -wlf wave_file1.wlf -l test1.log  -sv_seed random  work.ring_top +UVM_TESTNAME=ring_test
	vcover report  -cvg  -details -nocompactcrossbins -codeAll -assert -directive -html mem_cov1
	
run_test1_Questa:sv_cmp
	vsim -cvgperinstance $(VSIMOPT) $(VSIMCOV) $(VSIMBATCH2) $(VERBOSITY) -wlf wave_file2.wlf -l test2.log  -sv_seed random  work.ring_top +UVM_TESTNAME=verify_ring_counter
	vcover report  -cvg  -details -nocompactcrossbins -codeAll -assert -directive -html mem_cov2
	
view_wave1_Questa:
	vsim -view wave_file1.wlf
	
view_wave2_Questa:
	vsim -view wave_file2.wlf
	
report_Questa:
	vcover merge mem_cov mem_cov1 mem_cov2
	vcover report -cvg -details -nocompactcrossbins -codeAll -assert -directive -html mem_cov

regress_Questa: clean_Questa run_test_Questa run_test1_Questa report_Questa 

cov_Questa:
	firefox covhtmlreport/index.html&
	
clean_Questa:
	rm -rf transcript* *log* fcover* covhtml* mem_cov* *.wlf modelsim.ini work
	clear

# ----------------------------- End of Definitions for Mentor's Questa Specific Targets -------------------------------#



